---
- name: checking for agent install
  stat:
    path:
  register: agent

- debug:
    msg: "endgame agent not found (installing)"
  when: not agent.stat.exists

- debug:
    msg: "endgame agent found (skipping install)"
  when: agent.stat.exists

- name: create {{ redhat_endgame_agent_path }} directory
  file:
    path: '{{ redhat_endgame_agent_path }}'
    recurse: yes
    state: directory
    mode: 0500
  when: not agent.stat.exists

- name: install endgame agent (redhat)
  yum:
    name: '{{ redhat_endgame_agent_url }}'
    state: present
    validate_certs: no
    disable_plugin: "yum-rhn-plugin"
    disablerepo: "*"
    download_dir: '{{ redhat_endgame_agent_path }}'
  when: not agent.stat.exists

- name: copy actionsite.afxm to {{ redhat_endgame_agent_path }} directory
  get_url:
    url: '{{ endgame_actionsite_url }}'
    dest: '{{ redhat_endgame_agent_path }}/actionsite.afxm'
    validate_certs: no
    mode: '0755'
  when: not agent.stat.exists

- name: verify endgame started
  service:
    name:
    enabled: yes
    state: started
