---
- name: checking for agent install
  stat:
    path: /usr/sbin/esensor
  register: agent

- debug:
    msg: "endgame agent not found (installing)"
  when: not agent.stat.exists

- debug:
    msg: "endgame agent found (skipping install)"
  when: agent.stat.exists

- name: copy endgame.cfg to /tmp directory
  get_url:
    url: '{{ endgame_config_url }}'
    dest: '/tmp/endgame.cfg'
    validate_certs: no
    mode: '0755'
  when: not agent.stat.exists

- name: install endgame agent (redhat)
  shell: |
    '{{ redhat_endgame_agent_url }}'
    -k '{{ agent_secrets.endgame_key }}'
    -c '/tmp/endgame.cfg'
  args:
    creates: /usr/sbin/esensor
  when: not agent.stat.exists

- name: verify endgame started
  service:
    name: ensensor
    enabled: yes
    state: started
